### ISSUE TITLE
Glob Handling

### ISSUE THREAD

**Issue by 0xtekgrinder** [astrodevs-labs/osmium#181]
### Description

The goal of the task is to change the way the solidity linter is handling files by inputting a glob directly as argument.

### Definition of Done

- [ ] 1. the argument of file should be able to take a glob

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xSwapFeeder** [comment]
Wonder if this as not been taken care of in #187, can anybody attest of that ?

**Comment by 0xMemoryGrinder** [comment]
Already done
