### ISSUE TITLE
Refactor solidhunter

### ISSUE THREAD

**Issue by 0xMemoryGrinder** [astrodevs-labs/osmium#75]
### Title

Refactor solidhunter codebase

### Description

Refactor the solidhunter core lib codebase on the following aspects : 
- error management to now use thiserror
- global genericity of code
- rule engine and reporting

### QA

- [ ] The codebase now has state of the art error handling
- [ ] The codebase does not have duplicated code and boilerplate return value management
- [ ] The rule engine and LSP handling are clearly separated in two crates

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xSwapFeeder** [comment]
What do you consider LSP concerning the rule engine refactor ?
Because there is no LSP logic at all in the linter at the moment (besides either returning a diagnose or outputing it).

@0xMemoryGrinder @0xtekgrinder

**Comment by 0xMemoryGrinder** [comment]
> What do you consider LSP concerning the rule engine refactor ?
> Because there is no LSP logic at all in the linter at the moment (besides either returning a diagnose or outputing it).
> 
> For me LSP is the Rust server made with tower-lsp by @ByFishh.
> 
> @0xMemoryGrinder @0xtekgrinder

I specifically wrote the contrary : they have nothing in common, so they should be in two clearly separated unit

**Comment by 0xSwapFeeder** [comment]
> > What do you consider LSP concerning the rule engine refactor ?
> > Because there is no LSP logic at all in the linter at the moment (besides either returning a diagnose or outputing it).
> > 
> > For me LSP is the Rust server made with tower-lsp by @ByFishh.
> > 
> > @0xMemoryGrinder @0xtekgrinder
> 
> I specifically wrote the contrary : they have nothing in common, so they should be in two clearly separated unit
> @0xSwapFeeder 

Okay, so we agree on the fact that they already are separated crates right ?

**Comment by 0xMemoryGrinder** [comment]
Yes
