### ISSUE TITLE
Extentions CIs

### ISSUE THREAD

**Issue by 0xSwapFeeder** [astrodevs-labs/osmium#8]
### Description

Implement a CI to tests extensions and avoid regressions

### Definition of Done

- [ ] 1. Create a CI template
- [ ] 2. Implement units tests for all extensions based on the template
- [ ] 3. Setup automated units tests execution after each commit
- [ ] 4. Automated deployment of a specific branch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMemoryGrinder** [comment]
Already done
